---

- name: aws autoscaling complete-lifecycle-action --lifecycle-action-result CONTINUE --lifecycle-hook-name {{ HookName }} --auto-scaling-group-name {{ AsgName }} --lifecycle-action-token {{ ActionToken }} --region {{ AWSregion }}
  ansible.builtin.shell:
    cmd: aws autoscaling complete-lifecycle-action --lifecycle-action-result CONTINUE --lifecycle-hook-name {{ HookName }} --auto-scaling-group-name {{ AsgName }} --lifecycle-action-token {{ ActionToken }} --region {{ AWSregion }}
  run_once: true
