plugin: aws_ec2
regions:
  - ap-southeast-2
groups:
  niginx: tags.get('ansible-target') == 'nginx'
hostnames:
# a list in order of precedence for hostname variables.
#
  - ip-address
  - dns-name
  - tag:Name
  - private-ip-address
compose:
  ansible_host: private_ip_address
