---
- name: Ensure httpd is installed.
  package:
    name: httpd
    state: present

- name: Get ec2 facts
  ec2_metadata_facts:

- name: Copy index.html into place
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644

- name: Start httpd service
  service:
    name: httpd
    state: started
    enabled: true
