plugin: aws_ec2
regions:
  - ap-southeast-2
groups:
  apache: tags.get('ansible-target') == 'apache'
hostnames:
# a list in order of precedence for hostname variables.
#
  - private-ip-address
  - ip-address
  - dns-name
  - tag:Name
compose:
  ansible_host: private_ip_address
  # ansible_host: ip_address
